### PR TITLE
Naming and wording

### PR DESCRIPTION
**Pull request by miesgre**
Issue #32 

Made changes in `paella-core`, `paella-basic-plugins` and `paella-slide-plugins`

- https://github.com/polimediaupv/paella-core/commit/3f829ee26a360cd536b9d54685a5628e90a65599
- https://github.com/polimediaupv/paella-basic-plugins/commit/17066bbc6d4a574f2aa406744c2bc05522961827
- https://github.com/polimediaupv/paella-slide-plugins/commit/2454dd97841cff2774f2654272870a48330b95d3

Merge this pull request when the new versions are released

### CODE REVIEW

**Comment by miesgre** [comment]
All changes for ethz wording should go here: https://github.com/polimediaupv/paella-ethz/tree/main/src/i18n

You can edit there files and make a Pull request if you want or you can comment here and I will update the labels.

**Comment by oas777** [comment]
Hello Miguel

Does https://github.com/polimediaupv/paella-ethz/tree/main/src/i18n only have "changes" to the wording in "ethz" compared to the standard player? Because I only see four entries there. 

And if so, are these changes compared to 
- https://github.com/polimediaupv/paella-core/tree/main/src/i18n
- https://github.com/polimediaupv/paella-basic-plugins/tree/main/src/i18n
- https://github.com/polimediaupv/paella-slide-plugins/tree/main/src/i18n
- https://github.com/polimediaupv/paella-zoom-plugin/tree/main/src/i18n

for the English "original" wording? 

If that's the case, I should probably start there and update/harmonise the English version before translating to German.

**Comment by miesgre** [comment]
Yes,
In https://github.com/polimediaupv/paella-ethz/tree/main/src/i18n are only the changes for `ethz`.

If there is no translation in that `eth translations`  for a `key`, the default provided in paella libraries are used:
- https://github.com/polimediaupv/paella-core/tree/main/src/i18n
- https://github.com/polimediaupv/paella-basic-plugins/tree/main/src/i18n
- https://github.com/polimediaupv/paella-slide-plugins/tree/main/src/i18n
- https://github.com/polimediaupv/paella-zoom-plugin/tree/main/src/i18n

For instance, If `ethz` wants to change a wording it can be done without change it in the `paella library`.

https://github.com/polimediaupv/paella-ethz/blob/e27c75ef3246d9fa5bccd98eeef1426b3575dd7f/src/i18n/en-US.json#L1-L5

**Comment by oas777** [comment]
Thanks for your patience. I made and committed some changes, not sure whether I did it correctly though.

**Comment by miesgre** [comment]
You forgot the comma. Corrected in commit https://github.com/polimediaupv/paella-ethz/commit/b59f886692b6ea711b25f5e68df71ee9d3faaeb9

**Pull request merged**
